#! /usr/bin/expect

# this can push your target to the remote repository, but the local
# push record will not be updated, this is not a function problem,
# but it's annoying

set timeout 8
spawn git push origin master
expect "Username for 'http://git.oschina.net': "
send "wxlite\n"
set timeout 2
expect "Password for 'http://wxlite@git.oschina.net': "
send "mega328\n"
# maybe you should expect some output of git here
expect eof
exit
